name = "ApproxMasEq"
uuid = "2c63756f-059b-4317-898b-deccfd752643"
authors = ["David Machado"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
